### ISSUE TITLE
npm install outdated

### ISSUE THREAD

**Issue by pixtop** [jjclark1982/factorio-control-panel#2]
Hello, when I use the command line '_npm install -g factorio-control-panel_' , package is installed correctly but when I check the version in the file '_.travis.yml_' , version is 13.0.0 and I have an error with "--allow-command' and create save problem. What do you suggest to me ?
I'm working on a Debian 8 Jessie 64x Dedicated Server by OVH

**Comment by jjclark1982** [comment]
I hadn't published the current version to NPM. I have done so now, and you should be able get it by running

```
npm install -g factorio-control-panel@1.5.1
```
